name: arcadia_app
description: A new Flutter project..
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_arc_text: ^0.5.0
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  go_router: ^7.1.1
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.34
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0
  universal_html: ^2.2.2
  window_manager: ^0.3.4

dev_dependencies:
  build_runner: ^2.4.4
  flutter_gen: ^5.3.1
  flutter_lints:
    git: https://github.com/Sockitos/flutter_lints/
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/props/
    - assets/audios/
    - assets/audios/en/
    - assets/audios/pt/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: QuotesScript
      fonts:
        - asset: assets/fonts/QuotesScript-Regular.otf
          weight: 400
