name: arcadia_app
description: A new Flutter project..
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flip_card: ^0.6.0
  flutter:
    sdk: flutter
  flutter_arc_text: ^0.5.0
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  go_router: ^4.1.0
  hooks_riverpod: ^1.0.4
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  just_audio: ^0.9.27
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  universal_html: ^2.0.8
  window_manager: ^0.2.5

dev_dependencies:
  build_runner: ^2.1.11
  flutter_gen: ^4.3.0
  flutter_lints:
    git: https://github.com/Sockitos/flutter_lints/
  flutter_test:
    sdk: flutter

flutter_gen:
  line_lenght: 80

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/props/
    - assets/audios/
    - assets/audios/en/
    - assets/audios/pt/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: QuotesScript
      fonts:
        - asset: assets/fonts/QuotesScript-Regular.otf
          weight: 400
