name: arcadia_app
description: A new Flutter project..
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  audioplayers: ^1.0.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_arc_text: ^0.5.0
  flutter_circular_text: ^0.3.1
  flutter_hooks: ^0.18.4
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  go_router: ^3.1.0
  hooks_riverpod: ^1.0.4
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  smooth_page_indicator: ^1.0.0+2
  window_manager: ^0.2.3

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.10
  flutter_gen: ^4.1.6
  flutter_lints:
    git: https://github.com/Sockitos/flutter_lints/
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter_gen:
  line_lenght: 80

flutter:
  uses-material-design: true
  assets:
    - assets/images/backgrounds/
    - assets/images/props/
    - assets/audios/en/
    - assets/audios/pt/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: QuotesScript
      fonts:
        - asset: assets/fonts/QuotesScript-Regular.otf
          weight: 400
